import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "El Titular | Mar del Plata",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <meta
          name="google-site-verification"
          content="BsK1h2ZdQyS5zYzL0pUqqfivdjZDwThhi3n6lnRiQX4"
        />
      </body>
    </html>
  );
}
