import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "El Titular | Mar del Plata",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Script de Google Analytics */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-TN9LGG25FT"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-TN9LGG25FT');
            `,
          }}
        />
      </head>
      <body>
        {children}
        <meta
          name="google-site-verification"
          content="BsK1h2ZdQyS5zYzL0pUqqfivdjZDwThhi3n6lnRiQX4"
        />
      </body>
    </html>
  );
}
